name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: make prepare
    - name: Build
      run: make build
    - name: Run CI
      run: cd tests && cargo test

